/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/box.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Box(props) {
  const { nodes, materials } = useGLTF('/box.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cardboard_box001.geometry} material={materials.cardboard_box} position={[-1.351, -0.499, 2.399]} rotation={[0, 1.286, 0]} />
    </group>
  )
}

useGLTF.preload('/box.glb')
