/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/car.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Car(props) {
  const { nodes, materials } = useGLTF('/car.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box003.geometry} material={materials.wire_135059008} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Box014.geometry} material={materials.wire_177148027} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Box015.geometry} material={materials.wire_177148027} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Box001.geometry} material={materials.wire_166229229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Box016.geometry} material={materials.wire_086086086} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Box017.geometry} material={materials.wire_027177027} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.wire_027177148} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.wire_108008136} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.wire_214229166} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.wire_228184153} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.wire_228184153} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.wire_228184153} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.wire_108008136} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.wire_214229166} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.wire_061135006} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.wire_229166215} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder042.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder043.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder044.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder045.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder046.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder047.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder048.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder049.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder050.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder051.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder052.geometry} material={materials.wire_184228153} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder053.geometry} material={materials.wire_177027088} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder054.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder055.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder056.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder057.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder058.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder059.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder060.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder061.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder062.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder063.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder064.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder065.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder066.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder067.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder068.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder069.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder070.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder071.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder072.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder073.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder074.geometry} material={materials.wire_184228153} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder075.geometry} material={materials.wire_177027088} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder076.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder077.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder078.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder079.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder080.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder081.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder082.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder083.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder084.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder085.geometry} material={materials.wire_143225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder086.geometry} material={materials.wire_087225143} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder087.geometry} material={materials.wire_088088225} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder088.geometry} material={materials.wire_154154229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder089.geometry} material={materials.wire_154154229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Cylinder090.geometry} material={materials.wire_154154229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Line001.geometry} material={materials.wire_027177148} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Line003.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Line005.geometry} material={materials.wire_088088225} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Line006.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Line007.geometry} material={materials.wire_088088225} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Line008.geometry} material={materials.wire_057008136} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object002.geometry} material={materials.wire_000000000} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object005.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object009.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object012.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object015.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object016.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object018.geometry} material={materials.wire_108008136} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object019.geometry} material={materials.wire_108008136} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object020.geometry} material={materials.wire_027177148} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object021.geometry} material={materials.wire_027177148} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object022.geometry} material={materials.wire_224086086} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object023.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object024.geometry} material={materials.wire_229166215} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object025.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object026.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object027.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object028.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object029.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object030.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object031.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object032.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object033.geometry} material={materials.wire_008061138} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object036.geometry} material={materials.wire_154154229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object037.geometry} material={materials.wire_154154229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object038.geometry} material={materials.wire_087225143} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object039.geometry} material={materials.wire_088088225} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object040.geometry} material={materials.wire_000000000} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object041.geometry} material={materials.wire_000000000} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object042.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object043.geometry} material={materials.wire_006135113} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Object044.geometry} material={materials.wire_000000000} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane006.geometry} material={materials.wire_224086086} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane007.geometry} material={materials.wire_135059008} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane008.geometry} material={materials.wire_006135113} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane009.geometry} material={materials.wire_154154229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane010.geometry} material={materials.wire_028028177} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane011.geometry} material={materials.wire_028028177} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane016.geometry} material={materials.wire_225198087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane017.geometry} material={materials.wire_228153184} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane018.geometry} material={materials.wire_198225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane019.geometry} material={materials.wire_154185229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane020.geometry} material={materials.wire_138008110} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane024.geometry} material={materials.wire_008008136} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane025.geometry} material={materials.wire_008110135} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane027.geometry} material={materials.wire_088177027} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane029.geometry} material={materials.wire_225143087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane030.geometry} material={materials.wire_225198087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane031.geometry} material={materials.wire_228153184} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane032.geometry} material={materials.wire_198225087} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane033.geometry} material={materials.wire_135059008} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane034.geometry} material={materials.wire_225087143} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane035.geometry} material={materials.wire_135059008} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane037.geometry} material={materials.wire_087225198} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane038.geometry} material={materials.wire_184155229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane039.geometry} material={materials.wire_006135058} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane040.geometry} material={materials.wire_229166215} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane041.geometry} material={materials.wire_184155229} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane042.geometry} material={materials.wire_006135058} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane043.geometry} material={materials.wire_229166215} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane146.geometry} material={materials.wire_027177148} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane147.geometry} material={materials.wire_008008136} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane151.geometry} material={materials.wire_006135058} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane152.geometry} material={materials.wire_006135113} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Plane153.geometry} material={materials.wire_008008136} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Shape001.geometry} material={materials.wire_135059008} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Shape002.geometry} material={materials.wire_135059008} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Shape003.geometry} material={materials.wire_135059008} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Shape004.geometry} material={materials.wire_135059008} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
      <mesh geometry={nodes.Shape006.geometry} material={materials.wire_135059008} position={[1.047, -0.502, -0.476]} rotation={[-0.001, 0, 0]} scale={[0.417, 0.386, 0.391]} castShadow receiveShadow />
    </group>
  )
}

useGLTF.preload('/car.glb')
