/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/shelf.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shelf(props) {
  const { nodes, materials } = useGLTF('/shelf.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.479, 0.646, 2.425]} rotation={[Math.PI, -0.989, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.667, 0.646, 3.237]} rotation={[0, 0.411, 0]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.663, 0.646, 3.024]} rotation={[Math.PI, -0.429, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.493, 0.646, 3.121]} rotation={[Math.PI, -0.035, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.484, 0.646, 2.67]} rotation={[Math.PI, -0.035, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.655, 0.646, 2.61]} rotation={[Math.PI, -0.429, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.484, 0.771, 2.837]} rotation={[-1.322, -0.21, -2.26]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.976, 0.646, 2.577]} rotation={[Math.PI, -0.989, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.825, 0.646, 2.943]} rotation={[Math.PI, -0.989, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.997, 0.646, 2.94]} rotation={[0, 0.411, 0]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.994, 0.646, 2.762]} rotation={[Math.PI, -0.429, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.822, 0.646, 2.766]} rotation={[Math.PI, -0.035, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.829, 0.646, 3.115]} rotation={[Math.PI, -0.035, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-3.001, 0.646, 3.111]} rotation={[Math.PI, -0.429, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-3.004, 0.646, 3.289]} rotation={[0, 0.411, 0]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.832, 0.646, 3.292]} rotation={[Math.PI, -0.989, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.57, 1.151, 2.771]} rotation={[Math.PI, -0.035, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.825, 1.151, 2.943]} rotation={[Math.PI, -0.989, Math.PI]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.664, 1.151, 3.078]} rotation={[0, 0.411, 0]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.705, 1.184, 3.27]} rotation={[1.444, 0.299, 0.408]}>
        <mesh geometry={nodes.can_closed001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_closed001_1.geometry} material={materials['can_sticker.001']} />
      </group>
      <group position={[-2.664, 1.147, 2.887]} rotation={[Math.PI, -0.201, Math.PI]}>
        <mesh geometry={nodes.can_open001.geometry} material={materials['can_metal.001']} />
        <mesh geometry={nodes.can_open001_1.geometry} material={materials['can_sticker.001']} />
      </group>


      {nodes?.Shelf_holders001 && materials?.['rusted metal _ green.001'] && (
        <mesh
          geometry={nodes.Shelf_holders001.geometry}
          material={materials['rusted metal _ green.001']}
          position={[-2.316, -0.49, 3.45]}
          rotation={[0, 1.551, 0]}
        />
      )}
      {nodes?.Shelf_plate001 && materials?.['rusted_metal_Less.001'] && (
        <mesh
          geometry={nodes.Shelf_plate001.geometry}
          material={materials['rusted_metal_Less.001']}
          position={[-2.682, -0.369, 2.432]}
          rotation={[0, 1.551, 0]}
        />
      )}  </group>
  )
}

useGLTF.preload('/shelf.glb')
